### ISSUE TITLE
IntranetUserJS: Varaustunnuksen luonti ja siirto asiakkaan tiedot-listan loppuun

### ISSUE THREAD

**Issue by lmstrand** [KohaSuomi/koha-plugin-intranetjs-holdid#1]
Testaus:

Poista intranetUserJS-asetuksesta rimpsut:
// Varaustunnus-asiakasmääreen siirto asiakkaan muokkausnäytöllä
ja
// Varaustunnuksen automaattinen generointi.

Laita plugin IntranetUserJS: HoldID aktiiviseksi ja katso, että varaustunnus muodostuu uuden asiakkaan luonnissa automaattisesti ja että sitä voi vaihtaa kolmesta pisteestä kentän vierestä ja että varaustunnus-määre on siirtynyt oikeaan paikkaan.

**Comment by pknuuti** [comment]
Testasin Vaaran nextillä. Poistin mainitut JS-rimpsut ja lisäsin pluginin aktiiviseksi. Tein uuden asiakkaan, jolle varaustunnus-määre oli valmiiksi oikeassa paikassa ja kolmesta pisteestä sen sai vaihdettua. Mutta tyhjennä-painike ei tee mitään missään vaiheessa, ei ennen tietojen tallennusta eikä sen jälkeenkään. Toki tunnuksen vaihtaminen onnistuu kirjoittamalla entisen tunnuksen päälle.

![2023kuvat 456](https://github.com/KohaSuomi/koha-plugin-intranetjs-holdid/assets/73887264/8d14ec46-4f5e-497f-b90e-811475ea2a72)

**Comment by Kati-Helle** [comment]
Helle-nextissä uudelle asiakastiedolle varaustunnus muodostuu automaattisesti.

Varaustunnus-kentän Tyhjennä-painike vie näytön alkuun tyhjentämättä Varaustunnus-kenttää. Tämä tapahtuu sekä tallentamattomalle että tallennetulle asiakastiedolle
![kuva](https://github.com/KohaSuomi/koha-plugin-intranetjs-holdid/assets/99952449/7f7a6691-2259-4468-8a14-474df577221c)

*Tiedoksi vielä, että Varaustunnus on hieman eri paikassa kuin tuotannossa

![kuva](https://github.com/KohaSuomi/koha-plugin-intranetjs-holdid/assets/99952449/c88f894d-4d64-4a57-8dd8-78b86eaa54c9)

**Comment by atarnus** [comment]
Outi-Nextillä myös muodostuu varaustunnus automaattisesti uudelle asiakkaalle, ja kolmesta pisteestä saa aina päivitetyn version myös. Tyhjennä-nappi tosiaan skrollaa vain ruudun yläreunaan, ei tee muuta.

Asiakkaan muokkauksessa ei näy kolmea pistettä, ja Tyhjennä-nappi käyttäytyy samalla tavalla.

**Comment by lmstrand** [comment]
Korjasin tyhjennä-napin toiminnan, päivitettynä nexteillä.

**Comment by Kati-Helle** [comment]
Helle-nextissä toimii nyt oikein: Tyhjennä-painike tyhjentää Varaustunnus-kentän eikä liikauta näkymää.
Toimii oikein sekä tallentamattomassa asiakastiedossa että tallennetun asiakastiedon muokkauksessa.

**Comment by MikkoLiimatainen** [comment]
Vaski-nextillä varaustunnuskenttä siirtyy oikeaan kohtaan, varaustunnus generoituu uudelle käyttäjälle automaattisesti ja tunnuksen generointi, sekä kentän tyhjennys toimivat.

Tuosta Hellen kenttien järjestyksen muutoksesta tuli mieleeni, että onko näiden plugareiden suoritusjärjestystä mahdollista muuttaa? IntranetUserJS:ssä koodit pystyttiin pistämään järjestykseen sen mukaan, oliko niissä keskinäisiä riippuvuuksia, mutta voiko plugarit järjestää keskenään ja suhteessa IntranetUserJS:ään niin, että tällaiset asiat voidaan ottaa huomioon? Oletan siis, että Hellessä on tuo käyttökielen siirto tuotannossa suoritettu varaustunnuksen siirron jälkeen ja nextillä plugari suoritetaan IntranetUserJS:n jälkeen, jolloin kenttien järjestys muuttuu.

**Comment by lmstrand** [comment]
Pluginit haetaan aakkosjärjestyksessä sen mukaan, mikä pluginin plugin_class on taulussa plugin_data. Nuo plugin_classit taas muodostuvat käytännössä pluginin hakemistorakenteesta, eli pluginien javascript-sisällön suorittamisjärjestystä voisi muuttaa tuolla keinoin (nimeämällä pluginien nimet->hakemistot esim. numeroimalla niitä). Ennen pluginien javascript-sisältöjä suoritetaan intranetUserJS-sisältö.

**Comment by lmstrand** [comment]
Kiitos testeistä. Tämä plugin on ok. Pitää miettiä, mitä tehdä Hellen tapauksessa, jos asiakasmääreiden sijainti tuottaa ongelmia. Kustomoitu versio intranetUserJS:ään?

**Comment by lmstrand** [comment]
Seuranta kimpoista, joissa rimpsut poistettu intranetUserJS-asetuksesta ja aktivoitu plugin. Kommentoi tikettiä, kun muutos on tehty omaan kimppaan:

- [x] Lappi
- [x] OUTI
- [x] Siili
- [x] Vaara
- [x] Lumme
- [x] Kyyti
- [x] Helle
- [x] Kirkes
- [x] Lastu
- [x] Vaski

**Comment by ReettaSiili** [comment]
Siilin nextillä tämä toimii muuten toivotulla tavalla, mutta jos yritän tallentaa asiakasta ilman varaustunnistetta, joka on pakollinen tieto, tuloksena on internal server error tai pitkän pyörittelyn jälkeen asiakas on kuitenkin tallentunut ilman varaustunnistetta. Onko bugi vai johtuuko vain nextin jostain puutteellisista asetuksista? Parempi olisi varmaan joku selkeä virheilmoitus.

Edit: Vai onko varaustunnisteen edes oltava pakollinen tieto?

**Comment by atarnus** [comment]
> Siilin nextillä tämä toimii muuten toivotulla tavalla, mutta jos yritän tallentaa asiakasta ilman varaustunnistetta, joka on pakollinen tieto, tuloksena on internal server error tai pitkän pyörittelyn jälkeen asiakas on kuitenkin tallentunut ilman varaustunnistetta. Onko bugi vai johtuuko vain nextin jostain puutteellisista asetuksista? Parempi olisi varmaan joku selkeä virheilmoitus.
> 
> Edit: Vai onko varaustunnisteen edes oltava pakollinen tieto?

Joo, näkyisi Outi-nextillä tapahtuvan sama. Testillä herjaa muiden kenttien tapaan kentän pakollisuudesta eikä päästä läpi, mutta nextillä ei näemmä validointi toimi enää.

**Comment by ElinaUotila** [comment]
Kirkes-Nextillä varaustunnuskenttä siirtyy oikeaan kohtaan, varaustunnus generoituu uudelle käyttäjälle automaattisesti ja tunnuksen generointi, sekä kentän tyhjennys toimivat. Jos kentän tyhjentää eikä laita tilalle mitään, tulee herja kentän pakollisuudesta eikä asiakkaan tietoja pääse tallentamaan. Eli nyt näyttää toimivan niin kuin pitää.

**Comment by LeenaKinnunen** [comment]
Lapin nextillä plugari päällä ja turhat IntranetuserJS-rimpsut poistettu. Toimii kuten pitää.

**Comment by LastuJanneS** [comment]
Lastussa testattu ja toimii.

**Comment by Tuomas-Kyyti** [comment]
Kyyti ok (peukutettu joskus aiemmin)

**Comment by atarnus** [comment]
Näyttäisi nyt pelaavan tuon varaustunnus-kentän validointikin, eli ei päästä tallentamaan tyhjää kenttää. Eli tällainen on fiksattu? Missä tuon kentän pakollisuustieto edes on, sillä ei näy BorrowerMandatoryFieldeissä?

**Comment by lmstrand** [comment]
Asiakasmääreet-osiossa HOLDID/Varaustunnus-asiakasmääreen muokkausasetuksissa on täppä "pakollinen".

**Comment by Kati-Helle** [comment]
Helle-nextissä varaustunnuksettoman asiakastiedon tallennuksesta 
Internal Server Error

Tuotannossa näin
![kuva](https://github.com/user-attachments/assets/00025c0a-358b-4a47-a83b-f8e5cba09d49)

**Comment by emta001** [comment]
> Helle-nextissä varaustunnuksettoman asiakastiedon tallennuksesta Internal Server Error
> 
> Tuotannossa näin ![kuva](https://private-user-images.githubusercontent.com/99952449/384301643-00025c0a-358b-4a47-a83b-f8e5cba09d49.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEwNTk4NTQsIm5iZiI6MTczMTA1OTU1NCwicGF0aCI6Ii85OTk1MjQ0OS8zODQzMDE2NDMtMDAwMjVjMGEtMzU4Yi00YTQ3LWE4M2ItZjhlNWNiYTA5ZDQ5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA4VDA5NTIzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNmN2QzNDE3ZmZjMzk1NThhZjBjZjlkN2Q4NWVjYzIxNTc2ZjY0OWU2MjAyODQ0YThjMDI4NjFlYTg5Y2NhMGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.dJnapoTP32FMbDm-s8Ux1-0iJ_NcEwdveFVYXY81Qno)

Tämä johtuu lomakkeen validoinnista, siinä menee edelleen jokin väärin. Sama ongelma oli siis tässä tiketissä https://github.com/KohaSuomi/Koha-24.05/issues/147. Tietysti kannoissa ei pitäisikään olla asiakkaita ilman varaustunnusta, joten nämä kai pitäisi korjata muutenkin siltä osin.

**Comment by atarnus** [comment]
Outissa tosiaan on tuo ongelma korjaantunut päivitysten myötä. Ei tulee enää erroria.

**Comment by emta001** [comment]
Juu, ilmesesti tuo Hellen ongelma ratkeaa, kun korjataan jokin CSS-piilotus.

**Comment by lmstrand** [comment]
/* Piilota Muut määreet ja tunnukset -kohta asiakkaan muokkauksesta */
body#pat_memberentrygen.pat fieldset#memberentry_patron_attributes.rows { display:none; }

Tämä kaikkien asiakasmääreiden piilotus rikkoo varaustunnuksen kentän tarkistuksen. Siitä pitää poissulkea varaustunnus, jos se on merkitty kimpassa pakolliseksi. Muuten tapahtuu tuo internal server error pakollisuusherjan sijasta.

**Comment by AnneliO** [comment]
> /* Piilota Muut määreet ja tunnukset -kohta asiakkaan muokkauksesta */ body#pat_memberentrygen.pat fieldset#memberentry_patron_attributes.rows { display:none; }
> 
> Tämä kaikkien asiakasmääreiden piilotus rikkoo varaustunnuksen kentän tarkistuksen. Siitä pitää poissulkea varaustunnus, jos se on merkitty kimpassa pakolliseksi. Muuten tapahtuu tuo internal server error pakollisuusherjan sijasta.

Melkeinpä suosittelisin koko tuon rimpsun poistamista IntranetUserCSS:stä koska nyt se piilottaa myös automaattitunnuksilta Automaattityyppi ja Automaatin toimittaja -asiakasmääreet näkyvistä. Niitä on kuitenkin suositeltu täytettäväksi automaattitunnuksilla. :)

**Comment by Kati-Helle** [comment]
Poistin rimpsun Helle-nextistä. 

Asiakkaan muokkausnäytölle ilmestyi Muut määreet ja tunnukset -osio
![kuva](https://github.com/user-attachments/assets/5c87c3c5-c9ef-4d1e-9d6d-c56454c3d29c)

**Comment by AnneliO** [comment]
> Poistin rimpsun Helle-nextistä.
> 
> Asiakkaan muokkausnäytölle ilmestyi Muut määreet ja tunnukset -osio ![kuva](https://private-user-images.githubusercontent.com/99952449/384346542-5c87c3c5-c9ef-4d1e-9d6d-c56454c3d29c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEwNjQ3MzIsIm5iZiI6MTczMTA2NDQzMiwicGF0aCI6Ii85OTk1MjQ0OS8zODQzNDY1NDItNWM4N2MzYzUtYzllZi00ZDFlLTlkNmQtYzU2NDU0YzNkMjljLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA4VDExMTM1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI3NmVkYTQ3YjcxMmIwMjMyYTk1ZWQ4Yjc4MTBmZmMzMWFhNDhjYjI4ZGM2OTQ5MTljYTZkODQwZWI0ZjNiY2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.fplGnSRDv2nbMWjvybpdsBez919BbtEk0dHek5cnlic)

Juu, tuon se rimpsu piilottaa. Se on henkilöasiakkailla tyhjä, mutta automaattitunnuksilla ei.

**Comment by AnneliO** [comment]
Tämä on kaikilla kunnossa, joten suljen tiketin.
